version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    command:
      - --innodb_file_per_table
      - --innodb_file_format=Barracuda
      - --innodb_large_prefix
      - --character-set-server=utf8mb4
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: rails:dev
    environment:
      DATABASE_HOST: db
    volumes:
      - ./api:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    working_dir: "/app"
    command: bash -c "cd /app && rm -f /tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8000:3000
    depends_on:
      - api
    tty: true
    working_dir: "/usr/src/app"
    command: bash -c "yarn start"

volumes:
  bundle:
    driver: local
